version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      zookeeper:
        condition: service_started

  logging_service:
    build:
      context: ./logging_service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      zookeeper:
        condition: service_started
      kafka:
        condition: service_started
      elasticsearch:
        condition: service_started
    environment:
      KAFKA_BROKER: "kafka:9092"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.6
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.6
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_started

